# Generated by Django 4.2.6 on 2023-11-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genaiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('document_extraction', 'global | document extraction'), ('document_translation', 'global | document translation'), ('bank_statement', 'global | bank statement'), ('ktp_extraction', 'global | ktp extraction'), ('image_extraction', 'global | image extraction')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
