# Generated by Django 4.2.6 on 2023-11-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genaiapp', '0002_rightssupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'default_permissions': (), 'managed': False, 'permissions': (('document_extraction', 'global | document extraction'), ('document_translation', 'global | document translation'), ('bank_statement', 'global | bank statement'), ('ktp_extraction', 'global | ktp extraction'), ('image_extraction', 'global | image extraction'), ('dashboard', 'global | dashboard'))},
        ),
    ]
