# Generated by Django 4.2.7 on 2023-11-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genaiapp', '0003_alter_rightssupport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'default_permissions': (), 'managed': False, 'permissions': (('document_extraction', 'global | document extraction'), ('document_translation', 'global | document translation'), ('bank_statement', 'global | bank statement'), ('ktp_extraction', 'global | ktp extraction'), ('image_extraction', 'global | image extraction'), ('knowledge_base', 'global | knowledge base'), ('dashboard', 'global | dashboard'))},
        ),
    ]
